/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IItemViewModel } from "./services/services";
export { IItemViewModel } from "./services/services";
export namespace Components {
    interface MyComponent {
        /**
          * The Dnn module id, required in order to access web services.
         */
        "moduleId": number;
    }
    interface MyEdit {
        /**
          * The item to create or edit.
         */
        "item": IItemViewModel;
        /**
          * Resets the form to insert a new item.
         */
        "resetForm": () => Promise<void>;
        /**
          * Sets focus on the first form element
         */
        "setFocus": () => Promise<void>;
    }
    interface MyItemDetails {
        /**
          * The item to display
         */
        "item": IItemViewModel;
    }
    interface MyItemsList {
        /**
          * Defines how many items to fetch per request.
          * @default 100
         */
        "pageSize": number;
        /**
          * Defines how many pixels under the fold to preload.
          * @default 1000
         */
        "preloadPixels": number;
    }
}
export interface MyEditCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyEditElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyEditElementEventMap {
        "itemCreated": any;
    }
    interface HTMLMyEditElement extends Components.MyEdit, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyEditElementEventMap>(type: K, listener: (this: HTMLMyEditElement, ev: MyEditCustomEvent<HTMLMyEditElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyEditElementEventMap>(type: K, listener: (this: HTMLMyEditElement, ev: MyEditCustomEvent<HTMLMyEditElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyEditElement: {
        prototype: HTMLMyEditElement;
        new (): HTMLMyEditElement;
    };
    interface HTMLMyItemDetailsElement extends Components.MyItemDetails, HTMLStencilElement {
    }
    var HTMLMyItemDetailsElement: {
        prototype: HTMLMyItemDetailsElement;
        new (): HTMLMyItemDetailsElement;
    };
    interface HTMLMyItemsListElement extends Components.MyItemsList, HTMLStencilElement {
    }
    var HTMLMyItemsListElement: {
        prototype: HTMLMyItemsListElement;
        new (): HTMLMyItemsListElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-edit": HTMLMyEditElement;
        "my-item-details": HTMLMyItemDetailsElement;
        "my-items-list": HTMLMyItemsListElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface MyComponent {
        /**
          * The Dnn module id, required in order to access web services.
         */
        "moduleId": number;
    }
    interface MyEdit {
        /**
          * The item to create or edit.
         */
        "item"?: IItemViewModel;
        /**
          * Fires up when an item got created.
         */
        "onItemCreated"?: (event: MyEditCustomEvent<any>) => void;
    }
    interface MyItemDetails {
        /**
          * The item to display
         */
        "item": IItemViewModel;
    }
    interface MyItemsList {
        /**
          * Defines how many items to fetch per request.
          * @default 100
         */
        "pageSize"?: number;
        /**
          * Defines how many pixels under the fold to preload.
          * @default 1000
         */
        "preloadPixels"?: number;
    }

    interface MyComponentAttributes {
        "moduleId": number;
    }
    interface MyItemsListAttributes {
        "pageSize": number;
        "preloadPixels": number;
    }

    interface IntrinsicElements {
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] } & OneOf<"moduleId", MyComponent["moduleId"], MyComponentAttributes["moduleId"]>;
        "my-edit": MyEdit;
        "my-item-details": MyItemDetails;
        "my-items-list": Omit<MyItemsList, keyof MyItemsListAttributes> & { [K in keyof MyItemsList & keyof MyItemsListAttributes]?: MyItemsList[K] } & { [K in keyof MyItemsList & keyof MyItemsListAttributes as `attr:${K}`]?: MyItemsListAttributes[K] } & { [K in keyof MyItemsList & keyof MyItemsListAttributes as `prop:${K}`]?: MyItemsList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-edit": LocalJSX.IntrinsicElements["my-edit"] & JSXBase.HTMLAttributes<HTMLMyEditElement>;
            "my-item-details": LocalJSX.IntrinsicElements["my-item-details"] & JSXBase.HTMLAttributes<HTMLMyItemDetailsElement>;
            "my-items-list": LocalJSX.IntrinsicElements["my-items-list"] & JSXBase.HTMLAttributes<HTMLMyItemsListElement>;
        }
    }
}
